//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace first.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int UserId { get; set; }
        public int Pid { get; set; }
        public string Username { get; set; }
        public string Pname { get; set; }
        public string Pmodel { get; set; }
        public string Pbrand { get; set; }
        public string Quantity { get; set; }
        public string Price { get; set; }
    }
}
