//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class choice
    {
        public int Id { get; set; }
        public int QuestionId { get; set; }
        public int AnsId { get; set; }
        public string Answer { get; set; }
    }
}
