//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Question
    {
        public int QuestionId { get; set; }
        [Required(ErrorMessage ="Required")]
       // [Display(Name ="Enter Question")]
        public string Question1 { get; set; }
    }
}
