//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rating.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rate
    {
        public int ActId { get; set; }
        public string Actorname { get; set; }
        public int rate1 { get; set; }
        public int rate2 { get; set; }
        public int rate3 { get; set; }
        public int rate4 { get; set; }
        public int rate5 { get; set; }
        public int total { get; set; }
    }
}
