//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medlogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int PatientId { get; set; }
        public string Patientname { get; set; }
        public string Problem { get; set; }
        public string Description { get; set; }
        public string Mobileno { get; set; }
        public string Address { get; set; }
        public string Doctorname { get; set; }
    }
}
