//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace Mobileshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lreg
    {
        public int UserId { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Username required")]
        public string Username { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Password required")]
        [DataType(DataType.Password)]
        [MinLength(6, ErrorMessage = "Minimum 6 characters required")]
        public string Password { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Repassword required")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Passwords do not match.")]
        public string Repassword { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Emailid required")]
        [DataType(DataType.EmailAddress)]
        public string Emailid { get; set; }
    }
}
