//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobileshop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Userreg
    {
        public int UserId { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "name required")]
        public string Name { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Dob required")]
        public System.DateTime Dob { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Mobileno required")]
        [RegularExpression("^[0-9+]{10}$")]
        public string Mobileno { get; set; }
        [EmailAddress(ErrorMessage = "Invalid email address.")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Emailid required")]
        public string Emailid { get; set; }
     
        [Required(AllowEmptyStrings = false, ErrorMessage = "Gender required")]
        public string Gender { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Address required")]
        public string Address { get; set; }
    }
}
